export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const SUBMIT_ESTATE = 'SUBMIT_ESTATE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const PROFILE = 'PROFILE';
export const MY_FOLLOWING = 'MY_FOLLOWING'
export const MY_TRANSACTION = 'MY_TRANSACTION'
export const MY_TRANSACTION_HISTORY = ' MY_TRANSACTION_HISTORY'